questions = [
    "Vypiš mi 2 studijních programů.",
    "Jaké events se vážou na uživatele?",
    "Chci eventy a uživatele",
    "Dej mi seznam událostí (events)",
    "Jaké jsou anglické názvy pro prvních 5 programů?",
    "Najdi studijní programy, které obsahují slovo 'informační'.",
    "Vypiš 5 studijních programů, které vytvořil uživatel s id `c23c7349-8c90-48a6-8178-5a21e06d997d`.",
    "Jaké předměty jsou v programu s ID `d1b7a2e0-2b1c-4f7d-8a4b-8a7c8d9e0a1f`?",
    "Jaké semestry má předmět s ID `f3a6b0c2-3e5f-4c9d-8d2a-1b2c3d4e5f60`?",
    "Ukaž mi 3 předměty, které mají anglický název začínající na 'Introduction'.",
    "Najdi předmět, který byl naposledy změněn po 1. lednu 2025.",
    "Seřaď programy podle data jejich vytvoření od nejnovějšího.",
    "Vypiš mi 20 studentů, kteří studují program s ID `d1b7a2e0-2b1c-4f7d-8a4b-8a7c8d9e0a1f`.",
    "Jaký je název programu, který studuje student s ID `a4c9d2f8-1d7e-4b3a-9c5f-8e0c1a2d3b4e`?",
    "Jaké zprávy byly poslány studentovi s ID `b5d0e3g9-2h8f-5i6j-7k4l-9m0n1o2p3q4r`?",
    "Zobraz mi 10 nejnovějších klasifikací.",
    "Najdi klasifikace studenta s ID `a4c9d2f8-1d7e-4b3a-9c5f-8e0c1a2d3b4e` v semestru s ID `e5f4g3h2-1i0j-9k8l-7m6n-5o4p3q2r1s0t`.",
    "Vypiš anglické názvy klasifikačních úrovní.",
    "Seznam všech klasifikací, které proběhly po 1. září 2025.",
    "Najdi klasifikace, kde je 'order' menší než 5.",
    "Vypiš 5 studentů, kteří byli naposledy změněni po 1. září 2025.",
    "Kdo vytvořil poslední klasifikační úroveň?",
    "Jaké lekce patří k tématu s ID `c4b3a2d1-e5f6-7a8b-9c0d-1e2f3a4b5c6d`?",
    "Jaký je typ lekce s ID `d2c1b0a9-f8e7-6d5c-4b3a-2d1c0b9a8e7f`?",
    "Ukaž mi 10 témat, které vytvořil uživatel s ID `c23c7349-8c90-48a6-8178-5a21e06d997d`.",
    "Vypiš mi všechny typy lekcí.",
    "Najdi témata v semestru s ID `e5f4g3h2-1i0j-9k8l-7m6n-5o4p3q2r1s0t`.",
    "Vypiš 10 nadcházejících událostí.",
    "Kdo se zúčastnil události s ID `b2a1c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d`?",
    "Najdi události, které začínají po 1. lednu 2026.",
    "Jaké jsou typy událostí?",
    "Vypiš mi všechny události, které jsou typu 'Lecture'.",
    "Najdi události, které se konají v místě 'Building A'.",
    "Jaká je doba trvání události s ID `a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d`?",
    "Ukaž mi 5 publikací spojených s předmětem s ID `f3a6b0c2-3e5f-4c9d-8d2a-1b2c3d4e5f60`.",
    "Najdi publikaci podle jejího vnějšího ID.",
    "Jaké jsou jména autorů pro publikaci s ID `g9h8i7j6-k5l4-m3n2-o1p0-q9r8s7t6u5v4`?",
    "Ukaž mi prvních 15 uživatelů.",
    "Vyhledej uživatele s jménem 'John Newbie'.",
    "Vypiš všechny typy akreditovaných programů.",
    "Jaké jsou externí ID pro událost s ID `c4b3a2d1-e5f6-7a8b-9c0d-1e2f3a4b5c6d`?",
    "Jaké externí ID má uživatel s ID `a4c9d2f8-1d7e-4b3a-9c5f-8e0c1a2d3b4e`?",
    "Jak se jmenuje uživatel s ID `a4c9d2f8-1d7e-4b3a-9c5f-8e0c1a2d3b4e`?",
    "Jaké informace o studentovi mohu získat?",
    "Jak mohu zjistit, kolik předmětů má daný program?",
    "Jaké externí ID jsou k dispozici pro konkrétní událost?",
    "Můžeš mi vyfiltrovat všechny události, které začínají v konkrétní den?",
    "Jak mohu vyhledat publikace podle jména autora?",
    "Jak získat data o studijních programech seřazená podle názvu?",
    "Můžeš mi zobrazit všechny události pro danou skupinu uživatelů?",
    "Dej mi seznam všech uživatelů.",
    "Jaké jsou všechny skupiny?",
    "Ukaž mi uživatele, jejichž jméno začíná na 'Zde'.",
    "Jaké jsou všechny události (events)?",
    "Jaký je seznam všech studijních programů?",
    "Můžeš mi vypsat všechny předměty?",
    "Jaké jsou všechny události v kalendáři?",
    "Kdo jsou všichni uživatelé v systému?",
    "Ukaž mi všechny skupiny.",
    "Jaké jsou všechny publikace?",
    "Seznam mi všechny semestry.",
    "Jaké jsou všechny klasifikace?",
    "Vypiš mi všechny lekce v databázi.",
    "Jaké typy lekcí existují?",
    "Jaké jsou všechny typy programů?",
    "Ukaž mi všechny typy událostí.",
    "Jaké jazyky se používají ve studijních programech?",
    "Jaké jsou všechny role v systému?",
    "Vypiš mi všechny autory publikací.",
    "Jaké dotazníky jsou k dispozici?",
    "Ukaž mi všechna externí ID.",
    "Jaké typy klasifikací existují?",
    "Jaké úrovně klasifikací existují?",
    "Jaké jsou všechny studijní plány?",
    "Kdo jsou všichni studenti?",
    "Jaké zprávy byly poslány v rámci programů?",
    "Seznam mi všechny formy programů.",
    "Jaké úrovně programů existují?",
    "Vypiš mi všechny předměty seřazené abecedně.",
    "Jaké jsou všechny konce semestrů?",
    "Ukaž mi všechny plány.",
    "Jaké jsou všechny role spojené s uživateli?",
    "Seznam mi všechny odpovědi na dotazníky.",
    "Jaké typy účtů existují v databázi?",
]
